//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationOutcomes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PublicSchoolPovertyEntities : DbContext
    {
        public PublicSchoolPovertyEntities()
            : base("name=PublicSchoolPovertyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<GraduationRate> GraduationRates { get; set; }
        public virtual DbSet<Poverty> Poverties { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<SocioeconomicStatu> SocioeconomicStatus { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<TestResult> TestResults { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
    }
}
