//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationOutcomes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public int TestResultId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> SocioeconomicStatusId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<decimal> PercentMetStandard { get; set; }
    
        public virtual District District { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual School School { get; set; }
        public virtual SocioeconomicStatu SocioeconomicStatu { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
